/**
 * Application constants - centralized location for all magic numbers and configuration values
 */

// Time-related constants
export const TIMEOUTS = {
  WINDOW_BLUR_HIDE_DELAY: 150,
  TEXTAREA_FOCUS_DELAY: 50,
  NOTIFICATION_DURATION: 2000,
  FLASH_ANIMATION_DURATION: 400,
  KEYBOARD_NAVIGATION_TIMEOUT: 3000,
  ERROR_MESSAGE_DURATION: 3000,
  SEARCH_INPUT_FOCUS_DELAY: 100,
  CURRENT_APP_TIMEOUT: 2000,
  NATIVE_PASTE_TIMEOUT: 1500,
  ACCESSIBILITY_CHECK_TIMEOUT: 3000,
  WINDOW_BOUNDS_TIMEOUT: 3000,
  ACTIVATE_PASTE_TIMEOUT: 3000,
  APPLESCRIPT_FALLBACK_TIMEOUT: 2000,
  MINIMUM_WINDOW_HIDE_DELAY: 5
} as const;

// Delay constants for various operations
export const DELAYS = {
  DEBOUNCED_SAVE: 2000,
  CRITICAL_SAVE: 500,
  DRAFT_SAVE_MULTIPLIER: 2,
  QUICK_SAVE_THRESHOLD: 200,
  DEFAULT_DRAFT_SAVE: 500
} as const;

// Size and limit constants
export const LIMITS = {
  MAX_PASTE_TEXT_BYTES: 1024 * 1024, // 1MB
  DEFAULT_MAX_VISIBLE_ITEMS: 20,
  MAX_HISTORY_ITEMS: 50,
  MAX_DISPLAY_ITEMS: 10,
  BACKUP_CLEANUP_DAYS: 7
} as const;

// UI-related constants
export const UI = {
  NOTIFICATION_FADE_DURATION: 300,
  NOTIFICATION_Z_INDEX: 10000,
  NOTIFICATION_MAX_WIDTH: 300,
  NOTIFICATION_PADDING: '12px 16px',
  NOTIFICATION_BORDER_RADIUS: '8px',
  NOTIFICATION_FONT_SIZE: '13px',
  NOTIFICATION_TOP_OFFSET: '16px',
  NOTIFICATION_RIGHT_OFFSET: '16px',
  WINDOW_Y_OFFSET: 100,
  CHARACTER_WARNING_THRESHOLD: 0.7,
  CHARACTER_ERROR_THRESHOLD: 0.9,
  HISTORY_MORE_PADDING: '8px 16px',
  HISTORY_MORE_FONT_SIZE: '11px',
  HISTORY_MORE_OPACITY: 0.4
} as const;

// Time calculation constants
export const TIME_CALCULATIONS = {
  MILLISECONDS_PER_MINUTE: 60000,
  MILLISECONDS_PER_HOUR: 3600000,
  MILLISECONDS_PER_DAY: 86400000,
  TIMESTAMP_BASE: 36,
  RANDOM_ID_START: 2,
  RANDOM_ID_END: 11
} as const;

// Default window dimensions
export const WINDOW_DEFAULTS = {
  WIDTH: 600,
  HEIGHT: 300
} as const;

// Logging configuration
export const LOGGING = {
  MAX_LOG_FILE_SIZE: 5 * 1024 * 1024, // 5MB
  MAX_LOG_FILES: 3
} as const;

// Export all constants as a single object for convenience
export const CONSTANTS = {
  TIMEOUTS,
  DELAYS,
  LIMITS,
  UI,
  TIME_CALCULATIONS,
  WINDOW_DEFAULTS,
  LOGGING
} as const;